stages:
  - compile
  - test
  - run

# Stage 1: Compile the C Program
compile_bgmi:
  stage: compile
  image: gcc:latest
  script:
    - gcc bgmi.c -o bgmi
    - echo "bgmi.c compiled successfully."
  artifacts:
    paths:
      - bgmi

# Stage 2: Test Python Dependencies
test_python:
  stage: test
  image: python:3.9
  before_script:
    - pip install flask pyTelegramBotAPI
  script:
    - python3 -m compileall keep_alive.py
    - python3 -m compileall N.py
    - echo "Python files passed syntax checks."

# Stage 3: Run the Applications
run_application:
  stage: run
  image: python:3.9
  services:
    - docker:dind
  before_script:
    - apt-get update && apt-get install -y gcc
    - gcc bgmi.c -o bgmi
    - pip install flask pyTelegramBotAPI
  script:
    - python3 keep_alive.py &
    - python3 N.py &
    - ./bgmi 127.0.0.1 8080 100
  only:
    - main
    
